### ISSUE TITLE
not generating _prott5 files

### ISSUE THREAD

**Issue by hcliedtke** [MetazoaPhylogenomicsLab/FANTASIA#3]
Hi, Im very excited about using fantasia, but I am running into an issue that I can't seem to get past. I am not terribly familiar with singularity containers, so I apologies if this is something trivial, but it seems to have problems generating the _prott5 files. There are warnings about python package versions, but i suspect that's not the real issue? Below what fantasia has been dumping into my terminal. Thank you so much for your help.

>> Opening FASTA file...
>> Converting FASTA file from multiline to single line and writing to file.
>> Done!
Input files can be found in /home/cliedtke/fantasia_pcu23/
Configuration files can be found in /home/cliedtke/fantasia_pcu23/config_files/
Initiating GO annotation prediction using ProtT5 model. Estimated memory usage of 112.9091 G
/opt/conda/envs/gopredsim/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
2024-03-08 17:03:59.496067: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.singularity.d/libs
2024-03-08 17:03:59.496133: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/opt/conda/envs/gopredsim/bin/bio_embeddings", line 5, in <module>
    from bio_embeddings.utilities.cli import main
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/bio_embeddings/__init__.py", line 14, in <module>
    import bio_embeddings.project
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/bio_embeddings/project/__init__.py", line 5, in <module>
    from bio_embeddings.project.umap import umap_reduce
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/bio_embeddings/project/umap.py", line 1, in <module>
    from umap import UMAP
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/umap/__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/umap/umap_.py", line 28, in <module>
    import numba
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
/opt/conda/envs/gopredsim/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
{'go': '/FANTASIA//goPredSim/data/GO/go_2022.obo', 'lookup_set': '/FANTASIA//goPredSim/data/prott5_goa_2022.h5', 'annotations': '/FANTASIA//goPredSim/data/goa_annotations/goa_annotations_2022.txt', 'targets': '/home/cliedtke/fantasia_pcu23/PECUL23A.pep_prott5/PECUL23A.pep_prott5_embeddings/reduced_embeddings_file.h5', 'onto': 'all', 'thresh': '1', 'modus': 'num', 'output': '/home/cliedtke/fantasia_pcu23/PECUL23A.pep_prott5/gopredsim_PECUL23A.pep_prott5'}
Traceback (most recent call last):
  File "/FANTASIA/goPredSim/predict_go_embedding_inference.py", line 49, in <module>
    main()
  File "/FANTASIA/goPredSim/predict_go_embedding_inference.py", line 15, in main
    test_embeddings = fu.read_embeddings(config_data['targets'])
  File "/FANTASIA/goPredSim/file_utils.py", line 48, in read_embeddings
    with h5py.File(embeddings_in, 'r') as f:
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/opt/conda/envs/gopredsim/lib/python3.9/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/home/cliedtke/fantasia_pcu23/PECUL23A.pep_prott5/PECUL23A.pep_prott5_embeddings/reduced_embeddings_file.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
GO annotation done
Formatting GO annotation to topGO-compatible format
Traceback (most recent call last):
  File "/FANTASIA/convert_topgo_format.py", line 36, in <module>
    f = open(args.go_annotations + '/' + 'gopredsim_' + args.prefix + '_prott5_1_' + category + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/cliedtke/fantasia_pcu23/PECUL23A.pep_prott5/gopredsim_PECUL23A.pep_prott5_1_bpo.txt'
Done
Full results can be found in /home/cliedtke/fantasia_pcu23/PECUL23A.pep_prott5
Final GO annotation can be found in /home/cliedtke/fantasia_pcu23/PECUL23A.pep_topgo.txt

**Comment by gmartinezredondo** [comment]
Hi! Thanks for the interest :)

Could you tell me if you're running it locally or on a cluster? I've also had problems related to Python version incompatibilities when I tried it in the cluster we usually work with but no issues when running it locally. I will take a look at one thing that may be related to your issue but it may be useful if you could give me more information.

Gemma

**Comment by hcliedtke** [comment]
Hi Gemma. Yes, sorry I should have provided more information. Correct. I am running fantasia on a server/cluster operating with Rocky Linux 9.3 (Blue Onyx). 

I pulled the .sif file with:

 $ singularity pull --arch amd64 library://gemma.martinezredondo/fantasia/fantasia:sha256.008720e1258e82f9461045fbc4996631bc6251f18a121c4f611f0637eaf68f5f

And I have the following version of singularity installed:

singularity-ce version 3.11.0+428-gc8984cd6d

Thank you so much for your help!

**Comment by gmartinezredondo** [comment]
Hi! Thanks for the info.

I've found how to fix it in the cluster we usually use and uploaded the fixed image. The link in the README where it's stored is the same but I think that the unique ID has changed for pulling it with the command you used.

Could you give it a try and tell me if it works for you?

**Comment by hcliedtke** [comment]
Hi Gemma, 

I pulled the new image (fantasia_sha256.06f759be1e48bf4f72aed0d4bb4fe2fd6e05774bb58131b131f0128c7b0efc84.sif) but I still get the same python version warnings and the pipeline subsequently fails in the same way as before.

**Comment by gmartinezredondo** [comment]
OK. I see the problem now. I will investigate how to fix it. Meanwhile, I have two options for you:
1. You can try entering the container and re-installing the library raising the error. 
```
singularity shell fantasia_sha256.06f759be1e48bf4f72aed0d4bb4fe2fd6e05774bb58131b131f0128c7b0efc84.sif
pip install numba
exit
```
2. Install manually following the instructions in the README.

**Comment by hcliedtke** [comment]
Hi Gemma, that solved the problem for me. Thanks so much.
